### ISSUE TITLE
Error 100028: Failed to Request when setting up plugin

### ISSUE THREAD

**Issue by reasland** [birkir/homebridge-plugin-eufy-security#39]
(node:10729) UnhandledPromiseRejectionWarning: Error: Request failed: https://security-app.eufylife.com/v1/passport/login -> 100028 - Failed to request.

When I setup the plugin it fails to start with the above error

Hitting the endpoint works in postman from a secondary account, but moment i try to launch plugin with an account it locks out with that error for 24 hours preventing sign-in, from app, website, and postman

**Comment by reasland** [comment]
Full Error

> (node:10729) UnhandledPromiseRejectionWarning: Error: Request failed: https://security-app.eufylife.com/v1/passport/login -> 100028 - Failed to request.
    at /usr/lib/node_modules/homebridge-plugin-eufy-security/node_modules/eufy-node-client/build/http/http.utils.js:24:15
    at Generator.next (<anonymous>)
    at fulfilled (/usr/lib/node_modules/homebridge-plugin-eufy-security/node_modules/eufy-node-client/build/http/http.utils.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:10729) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:10729) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by bmonninkhof** [comment]
why do you open a new Issue, did you not read the last issue?

**Comment by reasland** [comment]
? is there already an issue open for this issue
